# Generated by Django 5.0.4 on 2024-09-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_banner_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='banner_img',
        ),
    ]
