# Generated by Django 5.0.4 on 2024-09-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpost_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
